# Generated by Django 3.0.5 on 2020-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads_motorbike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('creation_date', models.DateField()),
                ('views', models.PositiveIntegerField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('seller_type', models.TextField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('engine_displacement', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('kilometers', models.PositiveIntegerField()),
                ('date_scraping', models.DateField()),
            ],
        ),
    ]
